"""Initial

Revision ID: dd43237369b2
Revises: 
Create Date: 2022-12-02 19:00:19.074602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd43237369b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telebot_users',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('telebot_tasks',
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('task_name', sa.String(length=30), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['telebot_users.chat_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telebot_tasks')
    op.drop_table('telebot_users')
    # ### end Alembic commands ###
